name: docs-build-action
description: Build & Upload documentation

inputs:
  storage-bucket:
    required: true
  storage-endpoint:
    required: true
  storage-access-key-id:
    required: true
  storage-secret-access-key:
    required: true
  storage-region:
    required: true
  src-root:
    default: "./"
  build-root:
    default: "./_docs-build"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm i @diplodoc/cli -g
      shell: bash
    - run: yfm -i ${{ inputs.src-root }} -o ${{ inputs.build-root }}
      shell: bash
    - name: Upload to S3
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          PREFIX="pr-${{ github.event.pull_request.number }}"
        else
          PREFIX="main"
        fi

        yfm publish \
          -i "${{ inputs.build-root }}" \
          --endpoint "${{ inputs.storage-endpoint }}" \
          --region "${{ inputs.storage-region }}" \
          --bucket "${{ inputs.storage-bucket }}" \
          --access-key-id "${{ inputs.storage-access-key-id }}" \
          --secret-access-key "${{ inputs.storage-secret-access-key }}" \
          --prefix "${PREFIX}/"
          
    # - name: Install AWS CLI
    #   run: |
    #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    #     unzip awscliv2.zip
    #     sudo ./aws/install
    #   shell: bash

    # - name: Configure AWS CLI
    #   run: |
    #     aws configure set aws_access_key_id ${{ secrets.DIPLODOC_ACCESS_KEY_ID }}
    #     aws configure set aws_secret_access_key ${{ secrets.DIPLODOC_SECRET_ACCESS_KEY }}
    #     aws configure set default.region ${{ variables.DIPLODOC_STORAGE_REGION }}
    #     aws configure set default.s3.endpoint_url ${{ variables.DIPLODOC_STORAGE_ENDPOINT }}
    #   shell: bash

    # - name: Delete PR-18 directory
    #   run: aws s3 rm s3://mekstack-test/pr-18/ --recursive
    #   shell: bash
