name: docs-build-action
description: Build & Upload documentation

inputs:
  revision:
    required: true
  project-name:
    required: true
  storage-bucket:
    required: true
  storage-endpoint:
    required: true
  storage-access-key-id:
    required: true
  storage-secret-access-key:
    required: true
  storage-region:
    required: true
  src-root:
    default: "./"
  build-root:
    default: "./_docs-build"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm i @diplodoc/cli -g
      shell: bash
    - run: yfm -i ${{ inputs.src-root }} -o ${{ inputs.build-root }}
      shell: bash
    - name: Upload to S3
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          PREFIX="pr-${{ github.event.pull_request.number }}"
        else
          PREFIX="main"
        fi

        yfm publish \
          -i "${{ inputs.build-root }}" \
          --endpoint "${{ inputs.storage-endpoint }}" \
          --region "${{ inputs.storage-region }}" \
          --bucket "${{ inputs.storage-bucket }}" \
          --access-key-id "${{ inputs.storage-access-key-id }}" \
          --secret-access-key "${{ inputs.storage-secret-access-key }}" \
          --prefix "${PREFIX}/"

        # Удаляем папки, которые не соответствуют открытым pull requests
        echo "Removing folders in S3 bucket: ${PREFIX}"
        
        FOLDERS=$(aws s3 ls s3://"${{ inputs.storage-bucket }}"/"${PREFIX}"/ --recursive | awk -F'/' '{print $2}' | uniq)

        # Выводим список папок для отладки
        echo "Folders in S3 bucket: ${FOLDERS}"

        OPEN_PRS=$(gh pr list --json number,state -q "is:open" | jq -r '.[].number')

        # Выводим список открытых pull requests для отладки
        echo "Open pull requests: ${OPEN_PRS}"

        # Удаляем папки, которые не соответствуют открытым pull requests
        for FOLDER in $FOLDERS; do
          PR_NUMBER=$(echo $FOLDER | cut -d'-' -f2)
          if [[ ! " $OPEN_PRS " =~ " $PR_NUMBER " ]]; then
            echo "Deleting folder: ${FOLDER}"
            aws s3 rm s3://"${{ inputs.storage-bucket }}"/"${PREFIX}"/"${FOLDER}" --recursive
          fi
        done
